// Viex.MyExpenses.Web/ClientApp/src/app/components/transaction-list/transaction-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { TransactionEntry } from 'src/app/models/TransactionEntry';

const template = /*html*/`
<div class="list-group list-group-flush">
  <app-transaction-item *ngFor="let item of transactions"
    [transaction]="item">
  </app-transaction-item>
</div>
`

@Component({
  selector: 'app-transaction-list',
  template,
})
export class TransactionListComponent implements OnInit {

  @Input() transactions: TransactionEntry[]

  constructor() { }

  ngOnInit(): void {
  }

}

// Viex.MyExpenses.Spa/ClientApp/src/components/TransactionList/TransactionList.vue
<template>
    <v-list>
        <TransactionItem v-for="(item, index) of transactions" :transaction="item" :key="index" class="mb-4"/>
    </v-list>
</template>

<script lang="ts">
import { TransactionEntry } from '@/models/TransactionEntry'
import { Component, Prop, Vue } from 'vue-property-decorator'

@Component
export default class TransactionListComponent extends Vue {
    @Prop({ default: () => [] }) transactions: TransactionEntry[]
}
</script>
